// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `new`, `new`, `new`, `process`, `process`, `push`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AudioEngine`, `HighPassFilter`, `LinearResampler`, `VadGate`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`

/// Daftarkan stream sink untuk menerima update level audio secara live.
Stream<AudioLevel> createAudioLevelStream() =>
    RustLib.instance.api.crateApiAudioCreateAudioLevelStream();

/// Daftar nama device input yang tersedia.
List<String> listInputDevices() =>
    RustLib.instance.api.crateApiAudioListInputDevices();

/// Daftar nama device output (speaker) yang tersedia.
List<String> listOutputDevices() =>
    RustLib.instance.api.crateApiAudioListOutputDevices();

/// Cek apakah virtual audio driver (NoisyBoy Audio atau BlackHole) terpasang di sistem.
bool isVirtualDriverInstalled() =>
    RustLib.instance.api.crateApiAudioIsVirtualDriverInstalled();

/// Dapatkan nama virtual output device jika tersedia.
String? getVirtualDeviceName() =>
    RustLib.instance.api.crateApiAudioGetVirtualDeviceName();

/// Aktif/nonaktifkan denoise secara live.
void setDenoise({required bool enabled}) =>
    RustLib.instance.api.crateApiAudioSetDenoise(enabled: enabled);

/// Status denoise saat ini.
bool isDenoiseOn() => RustLib.instance.api.crateApiAudioIsDenoiseOn();

/// Mulai loopback dengan denoise.
///
/// Memakai sample rate NATIVE tiap device (tidak dipaksa), lalu resample
/// ke 48kHz untuk nnnoiseless dan resample balik ke rate output. Ini
/// menghindari error "stream configuration not supported".
Future<String> startLoopback({String? deviceName, String? outputName}) =>
    RustLib.instance.api.crateApiAudioStartLoopback(
      deviceName: deviceName,
      outputName: outputName,
    );

/// Hentikan loopback.
Future<String> stopLoopback() =>
    RustLib.instance.api.crateApiAudioStopLoopback();

/// Apakah loopback sedang berjalan.
bool isRunning() => RustLib.instance.api.crateApiAudioIsRunning();

/// Data level audio untuk visualisasi VU meter / waveform di UI.
class AudioLevel {
  final double inputLevel;
  final double outputLevel;

  const AudioLevel({required this.inputLevel, required this.outputLevel});

  @override
  int get hashCode => inputLevel.hashCode ^ outputLevel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioLevel &&
          runtimeType == other.runtimeType &&
          inputLevel == other.inputLevel &&
          outputLevel == other.outputLevel;
}
