// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `new`, `push`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AudioEngine`, `LinearResampler`

/// Daftar nama device input yang tersedia.
List<String> listInputDevices() =>
    RustLib.instance.api.crateApiAudioListInputDevices();

/// Daftar nama device output (speaker) yang tersedia.
List<String> listOutputDevices() =>
    RustLib.instance.api.crateApiAudioListOutputDevices();

/// Aktif/nonaktifkan denoise secara live.
void setDenoise({required bool enabled}) =>
    RustLib.instance.api.crateApiAudioSetDenoise(enabled: enabled);

/// Status denoise saat ini.
bool isDenoiseOn() => RustLib.instance.api.crateApiAudioIsDenoiseOn();

/// Mulai loopback dengan denoise.
///
/// Memakai sample rate NATIVE tiap device (tidak dipaksa), lalu resample
/// ke 48kHz untuk nnnoiseless dan resample balik ke rate output. Ini
/// menghindari error "stream configuration not supported".
Future<String> startLoopback({String? deviceName, String? outputName}) =>
    RustLib.instance.api.crateApiAudioStartLoopback(
      deviceName: deviceName,
      outputName: outputName,
    );

/// Hentikan loopback.
Future<String> stopLoopback() =>
    RustLib.instance.api.crateApiAudioStopLoopback();

/// Apakah loopback sedang berjalan.
bool isRunning() => RustLib.instance.api.crateApiAudioIsRunning();
